"""
Auto-generated from assets/gakumasu-diff and localization JSON.
Do not edit manually; regenerate via devtools/generate_game_database_schemas.py.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List

@dataclass(slots=True)
class Setting:
    id: str = None
    giftDefaultLimitCount: int = None
    giftHistoryDefaultLimitCount: int = None
    meishiLimitCount: int = None
    meishiObjectLimitCount: int = None
    meishiFolderLimitCount: int = None
    newLabelTTL: int = None
    workSkipLimit: int = None
    workSkipConsumeMinutes: int = None
    profileBirthdayUpdateIntervalDays: int = None
    resetTimingHour: int = None
    resetTimingMinute: int = None
    resetTimingWeek: str = None
    resetTimingDay: int = None
    initialUserMeishiBaseAssetID: str = None
    rosterIgnoreReportDearnessLevels: List[int] = field(default_factory=list)
    memoryLimitCount: int = None
    photoLimitCount: int = None
    actionPointRecoveryMinutes: int = None
    actionPointMaxValue: int = None
    moneyHomeDisplayPermil: int = None
    moneyReceivableMinimumMinutes: int = None
    workExcellentRewardQuantityCoefficientPermil: int = None
    fanCountLimit: str = None
    workFineCharacterMaxCountInDay: int = None
    workFineProbabilityPermil: int = None
    workFineFixDays: int = None
    friendBaseFollowLimitCount: int = None
    friendFollowerLimitCount: int = None
    friendCoinMaxDailyAccumulationCount: int = None
    friendCoinSupportCardRentalRewardQuantity: int = None
    friendCoinMemoryRentalRewardQuantity: int = None
    memoryPowerParameterCoefficientPermil: int = None
    memoryPowerStaminaCoefficientPermil: int = None
    memoryPowerProduceResourceEvaluationCoefficientPermil: int = None
    seminarExamSettingID: str = None
    initialUserName: str = None
    towerExamSettingID: str = None
    coinGashaNoticeDrawCount: int = None
    jewelShopID: str = None
    missionPassPointExchangeJewel: int = None
    officialXURL: str = None
    iosFaqURL: str = None
    androidFaqURL: str = None
    initialAchievementID: str = None
    inviteUserActiveMaxCount: int = None
    invitationEnterCodeRewardJewelQuantity: int = None
    invitationEnterCodeRewardProvideConditionSetID: str = None
    iosInquiryURL: str = None
    androidInquiryURL: str = None
    invitationEnterCodeConditionSetID: str = None
    userDeleteInquiryURL: str = None
    invitationNoticeID: str = None
    banWarningMessage: str = None
    seminarInitialParameter: int = None
    memoryCreateAbilityRToSsrPermil: int = None
    memoryCreateAbilitySrToSsrPermil: int = None
    memoryCreateProduceCardSrToSsrPermil: int = None
    memoryCreateExamBattleProduceCardSrToSsrPermil: int = None
    musicHotDisplayCount: int = None
    homeDailyMissionGroupID: str = None
    homeWeeklyMissionGroupID: str = None
    memoryCreateParameterSmall: int = None
    memoryCreateParameterMiddle: int = None
    memoryCreateParameterLarge: int = None
    towerViewConditionSetID: str = None
    seminarViewConditionSetID: str = None
    storyEventTipsAssetIDs: List[str] = field(default_factory=list)
    storyEventPointLimit: int = None
    seminarGuidanceViewConditionSetID: str = None
    officialWebSiteURL: str = None
    iPPortalWebSiteURL: str = None
    photoNameLengthLimit: int = None
    homeEventEndTimeDisplayHour: int = None
    idolCardPieceExchangeItemID: str = None
    storyEventMainStoryTipsAssetIDs: List[str] = field(default_factory=list)
    officialDiscordURL: str = None
    officialYouTubeIdolMasterURL: str = None
    officialYouTubeHatsuBoshiURL: str = None
    storyEventGuildMissionTipAssetIDs: List[str] = field(default_factory=list)
    photoPoseWaitVoicePlayIntervalSeconds: int = None
    photoBackgroundDefaultBGMAssetID: str = None
    photoMaxShootingCount: int = None
    photoAutoShootingCount: int = None
    meishiEditCustomUnlockConditionSetID: str = None
    photoIdolViewConditionSetID: str = None
    gvgRaidScoreEffectMiddleThreshold: int = None
    gvgRaidScoreEffectLargeThreshold: int = None
    gvgRaidAuditionScoreUpMiddle: int = None
    gvgRaidAuditionScoreUpLarge: int = None
    photoFacialViewConditionSetID: str = None
    memoryReshootingValidateIdolCardTrueEndConditionSetID: str = None
    gashaAnimationLogicSwitchConditionSetID: str = None
    meishiEditCustomUpdateUnlockConditionSetID: str = None
    dmmGamesFaqURL: str = None
    dmmGamesInquiryURL: str = None
    towerRankingDisplayCount: int = None
    towerRankingDeckDisplayCount: int = None
    dearnessTopConditionSetID: str = None
    tourScoreEffectMiddleThreshold: int = None
    tourScoreEffectLargeThreshold: int = None
    tourAuditionScoreUpMiddle: int = None
    tourAuditionScoreUpLarge: int = None
    tourScoreGradeThreshold: int = None
    memoryInheritMaterialLowerResultGrade: int = None
    memoryInheritCustomizeProduceCardEnable: bool = None
    researchRankingDisplayCount: int = None
    homeCharacterRandomIdolViewConditionSetID: str = None
    badgeEditViewConditionSetID: str = None
    userBlockLimitCount: int = None
    sceneTransitionSDCharacterAnimationViewConditionSetID: str = None
    sceneTransitionSDCharacterAnimationFirstAssetIDs: List[str] = field(default_factory=list)
    sceneTransitionSDCharacterAnimationSecondAssetIDs: List[str] = field(default_factory=list)
    produceDailyMemoryRentalLimit: int = None
    produceDailyFreeContinueCount: int = None
    produceContinueItemID: str = None
    produceStartShopWarningProducePointQuantity: int = None
    produceParameterOutGameDisplayLimit: int = None
    produceParameterInGameDisplayLimit: int = None
    producePointLimit: int = None
    produceMaxStaminaLimit: int = None
    produceCardLimitCount: int = None
    produceRankingDisplayCount: int = None
    produceAuditionScoreUpMiddle: int = None
    produceAuditionScoreUpLarge: int = None
    produceExamBattleScorePenaltyMinPermil: int = None
    produceExamBattleScorePenaltyMaxPermil: int = None
    produceSupportCardRecommendLevelCoefficientPermils: List[int] = field(default_factory=list)
    produceSupportCardRecommendTypeNegativeCoefficientPermil: int = None
    producePictureBookLiveProduceGroupID: str = None
    produceRevealSpLessonStepCount: int = None
    produce3DTapSkipConditionSetID: str = None
    produceLessonParameterUpMiddle: int = None
    produceLessonParameterUpLarge: int = None
    produceExamProduceCardSuggestMinutes: int = None
    produceScheduleSelectPlaceStaminaThreshold: int = None
    produceMemoryRerollCount: int = None
    produceDeckNameLengthLimit: int = None
    produceDescriptionProduceStepCategoryEnable: bool = None
    produceCardEffectCancelEnable: bool = None
    produceMemoryProduceCardProducerLevelLimitDisable: bool = None
    produceSupportCardRecommendUsageRateRankAdditionValues: List[int] = field(default_factory=list)
    produceSupportCardRecommendTypePreferentialSlotCounts: List[int] = field(default_factory=list)
    produceSupportCardRecommendTypePreferentialCoefficientPermil: int = None
    produceSupportCardRecommendSpPreferentialSlotCounts: List[int] = field(default_factory=list)
    produceSupportCardRecommendSpPreferentialCoefficientPermil: int = None
    memoryCreateAbilityRToUrPermil: int = None
    memoryCreateAbilitySrToUrPermil: int = None
    memoryCreateAbilitySsrToUrPermil: int = None
    produceStepShopDiscountRoundDownEnable: bool = None
    produceAuditionTrendAssessmentPermilSeparateEnable: bool = None
    produceMaxMemoryDeckCount: int = None
    produceMaxSupportCardDeckCount: int = None
    gashaPickupStoryCampaignCharacterDearnessLevel: int = None
    gashaAnimationReversalSsrPermil: int = None
    gashaAnimationReversalPickUpProduceIdolSsrPermil: int = None
    tutorialSetNameAdvIndex: int = None
    tutorialIdolCardSkinSelectRewardID: str = None
    shopPurchasableLimitAmountThreshold1: int = None
    shopPurchasableLimitAmountThreshold2: int = None
    shopPurchaseAlertThreshold: int = None
    jewelMaxQuantityForPaid: int = None
    jewelMaxQuantityForFree: int = None
    shopPurchasableLimitAgeThreshold1: int = None
    shopPurchasableLimitAgeThreshold2: int = None
    shopExpireEmphasisHour: int = None
    guildMemberLimitCount: int = None
    guildJoinRequestLimitCount: int = None
    guildJoinRequestReceiveLimitCount: int = None
    guildRestrictJoinHour: int = None
    guildRestrictEstablishHour: int = None
    guildRestrictDonationRequestHour: int = None
    guildDonationRequestReceiveMaxQuantity: int = None
    guildDonationLimitCount: int = None
    guildNameLengthLimit: int = None
    guildDescriptionLengthLimit: int = None
    guildLeaderMessageLengthLimit: int = None
    profileNameLengthLimit: int = None
    profileCommentLengthLimit: int = None
    pvpRateSameCharacterDeckConditionSetID: str = None
    pvpRateMemoryRecommendParameterCoefficientPermil: int = None
    pvpRateMemoryRecommendStaminaCoefficientPermil: int = None
    pvpRateMemoryRecommendProduceCardCoefficientPermil: int = None
    pvpRateMemoryRecommendProduceItemCoefficientPermil: int = None
    pvpRateExamBattleAllSkipUnlockConditionSetID: str = None
    pvpRateRehearsalViewConditionSetID: str = None
    pvpRateRankingDisplayCount: int = None
    examBattleSubMemoryParameterPermil: int = None
    examBattleSubMemoryStaminaPermil: int = None
    examBattleConditionThresholdMultipleScore: int = None
    pushDailyMissionNotifyHour: int = None
    pushDailyMissionNotifyMinutes: int = None
    pushDailyMissionDoNotNotifyNoLoginDay: int = None
    pushNoLoginNotifyLatestIntervalHour: int = None
    pushPvpRateRemainingPlayCountNotifyHour: int = None
    pushPvpRateRemainingPlayCountNotifyMinutes: int = None
    pushPvpRateRemainingPlayCountDoNotNotifyNoLoginDay: int = None
    aprilFool2025TransitionStoryID: str = None
    aprilFool2025ProduceLiveMusicID: str = None
    produceNextIdolAuditionMasterRankingUnlockConditionSetID: str = None
    producerRankingUnlockConditionSetID: str = None
    producerRankingBGMAssetID: str = None
    producerRankingCharacterAnimationLowerLimitRank: int = None
    producerRankingTowerLayerHighScoreViewConditionSetID: str = None
    competitionMaxDeckCount: int = None
    competitionDeckNameLengthLimit: int = None
    competitionMaxDailyPlayCount: int = None
    competitionMaxContinueCount: int = None
    competitionDeckProduceCardRecommendRankAdditionValues: List[int] = field(default_factory=list)
    competitionExchangeAccessGrade: int = None
    competitionRecommendDeckBuffCoefficientPermil: int = None
    competitionNeedProduceCardCount: int = None
    competitionGradeUpgradeAnimationThresholdGrade: int = None
    competitionGradeStayAnimationThresholdGrade: int = None
    competitionBgmAssetID: str = None
    webStoreLinkURL: str = None
    webStoreShopBannerIOSDisplayEnable: bool = None
    webStoreShopBannerIOSAssetID: str = None
    webStoreShopBannerAndroidDisplayEnable: bool = None
    webStoreShopBannerAndroidAssetID: str = None
    localization: SettingLocalization = None

@dataclass(slots=True)
class SettingLocalization:
    id: str = None
    initialUserName: str = None
    banWarningMessage: str = None
