class ShopSubPage:
    GEM = "SHOP__GEM"
    PACK = "SHOP__PACK"
    PASS = "SHOP__PASS"
    COIN_GACHA = "SHOP__COIN_GACHA"
    DAILY_EXCHANGE = "SHOP__DAILY_EXCHANGE"
    COSTUME_EXCHANGE = "SHOP__COSTUME_EXCHANGE"
    ITEM_EXCHANGE = "SHOP__ITEM_EXCHANGE"
    TICKET_EXCHANGE = "SHOP__TICKET_EXCHANGE"

class AchievementSubPage:
    IDOL = "ACHIEVEMENT__IDOL"
    PRODUCER = "ACHIEVEMENT__PRODUCER"
    OTHER = "ACHIEVEMENT__OTHER"

class Producer:
    PRODUCER_REGULAR = "PRODUCER_REGULAR"
    PRODUCER_PRO = "PRODUCER_PRO"
    PRODUCER_MASTER = "PRODUCER_MASTER"
    PRODUCER_NIA = "PRODUCER_NIA"

class HomeTab:
    WORK = "WORK"
    GIFT = "GIFT"
    TASK = "TASK"
    MISSION_PASS = "MISSION_PASS"
    ACHIEVEMENT = "ACHIEVEMENT"
    ACHIEVEMENT_SUB_PAGR = AchievementSubPage
    SHOP = "SHOP"
    SHOP_SUB_PAGE = ShopSubPage
    PRODUCER = "PRODUCER"
    PRODUCER_SUB_PAGE = Producer
