class ShopSubPage:
    GEM = "SHOP__GEM"
    PACK = "SHOP__PACK"
    PASS = "SHOP__PASS"
    COIN_GACHA = "SHOP__COIN_GACHA"
    DAILY_EXCHANGE = "SHOP__DAILY_EXCHANGE"
    COSTUME_EXCHANGE = "SHOP__COSTUME_EXCHANGE"
    ITEM_EXCHANGE = "SHOP__ITEM_EXCHANGE"
    TICKET_EXCHANGE = "SHOP__TICKET_EXCHANGE"

class AchievementSubPage:
    IDOL = "ACHIEVEMENT__IDOL"
    PRODUCER = "ACHIEVEMENT__PRODUCER"
    OTHER = "ACHIEVEMENT__OTHER"

class Producer:
    PRODUCER_REGULAR = "PRODUCER_REGULAR"
    PRODUCER_PRO = "PRODUCER_PRO"
    PRODUCER_MASTER = "PRODUCER_MASTER"
    PRODUCER_NIA = "PRODUCER_NIA"
    PRODUCER__MEMORY_SELECTION = "PRODUCER__MEMORY_SELECTION"
    PRODUCER__MEMORY_CANDIDATE_LIST = "PRODUCER__MEMORY_CANDIDATE_LIST"
    PRODUCER__MEMORY_DETAIL = "PRODUCER__MEMORY_DETAIL"
    PRODUCER__FINAL_CONFIRM = "PRODUCER__FINAL_CONFIRM"
    PRODUCER__IDOL_SELECTION = "PRODUCER__IDOL_SELECTION"
    PRODUCER__SUPPORT_SELECTION = "PRODUCER__SUPPORT_SELECTION"
    PRODUCER__START_CONFIRMATION = "PRODUCER__START_CONFIRMATION"
    PRODUCER__FORMATION_DETAIL = "PRODUCER__FORMATION_DETAIL"
    PRODUCER__MEMORY_FORMATION_LIST = "PRODUCER__MEMORY_FORMATION_LIST"
    PRODUCER__SUPPORT_FORMATION_LIST = "PRODUCER__SUPPORT_FORMATION_LIST"

class HomeTab:
    WORK = "WORK"
    GIFT = "GIFT"
    TASK = "TASK"
    PASS_REWARD = "PASS_REWARD"
    ACHIEVEMENT = "ACHIEVEMENT"
    ACHIEVEMENT_SUB_PAGE = AchievementSubPage
    SHOP = "SHOP"
    SHOP_SUB_PAGE = ShopSubPage
    PRODUCER = "PRODUCER"
    PRODUCER_SUB_PAGE = Producer
